### ISSUE TITLE
Add Docker Support

### ISSUE THREAD

**Issue by mariushosting** [HermanMartinus/bearlytics#3]
Nice wonderful Project!

Please add Docker Support!

**Comment by vimwtf** [comment]
I put together a Docker image for running Bearlytics and it seems to be working well on my server. There's definitely room for polish and improvement (like using GitHub Actions to build the image and host it in ghcr.io) but this might be a good starting point.

https://github.com/jbowdre/bearlytics/tree/docker

I'm happy to tweak as needed and submit a PR if desired.

**Comment by HermanMartinus** [comment]
That would be great @jbowdre 👍

**Comment by mariushosting** [comment]
> I put together a Docker image for running Bearlytics and it seems to be working well on my server. There's definitely room for polish and improvement (like using GitHub Actions to build the image and host it in ghcr.io) but this might be a good starting point.
> 
> https://github.com/jbowdre/bearlytics/tree/docker
> 
> I'm happy to tweak as needed and submit a PR if desired.

Unable to find the image even in the example compose published.

**Comment by vimwtf** [comment]
> > I put together a Docker image for running Bearlytics and it seems to be working well on my server. There's definitely room for polish and improvement (like using GitHub Actions to build the image and host it in ghcr.io) but this might be a good starting point.
> > 
> > https://github.com/jbowdre/bearlytics/tree/docker
> > 
> > I'm happy to tweak as needed and submit a PR if desired.
> 
> Unable to find the image even in the example compose published.

You can build the image from the Dockerfile. I'll add usage notes to the readme before I send the PR. 

The short version is to add the required vars to a `.env` file, create the `analytics` folder to store the data, and run `docker compose up -d --build`. 

You'll probably want to serve this behind a reverse proxy (like caddy or nginx).

**Comment by mariushosting** [comment]
> > > I put together a Docker image for running Bearlytics and it seems to be working well on my server. There's definitely room for polish and improvement (like using GitHub Actions to build the image and host it in ghcr.io) but this might be a good starting point.
> > > https://github.com/jbowdre/bearlytics/tree/docker
> > > I'm happy to tweak as needed and submit a PR if desired.
> > 
> > 
> > Unable to find the image even in the example compose published.
> 
> You can build the image from the Dockerfile. I'll add usage notes to the readme before I send the PR.
> 
> The short version is to add the required vars to a `.env` file, create the `analytics` folder to store the data, and run `docker compose up -d --build`.
> 
> You'll probably want to serve this behind a reverse proxy (like caddy or nginx).

Yes, the only one thing is that we want an image already published on github. Don't have the time to maintain it.

**Comment by vimwtf** [comment]
Agreed, and that's the definitely my goal. What I've got so far is just the first major step along that path. I'll look at the workflow for building and publishing the image next.

**Comment by HermanMartinus** [comment]
Closed with https://github.com/HermanMartinus/bearlytics/pull/6
