### ISSUE TITLE
URL scheme missing from script embed code

### ISSUE THREAD

**Issue by vimwtf** [HermanMartinus/bearlytics#4]
I noticed that the script embed code displayed on the websites list is missing the URL scheme.

```html
<script data-site="XXXXXX" src="//example.com/script.js" defer></script>
```

instead of
```html
<script data-site="XXXXXXX" src="https://example.com/script.js" defer></script>
```

Adding `{{ request.scheme }}` to the [websites template](https://github.com/HermanMartinus/bearlytics/blob/d8a04ab5a8b680a9d70aca4b9ff1b28b6cb1ed0c/project/templates/websites.html#L30) allows the correct scheme to be loaded automatically.

Would you mind if I send a PR for this small tweak?
https://github.com/jbowdre/bearlytics/commit/a481d69e3ad6f7401b21a2c2814540f02f8b3017

**Comment by HermanMartinus** [comment]
Yeah, go ahead 👍
